### ISSUE TITLE
CreateNew by sylius.repository.product

### ISSUE THREAD

**Issue by marcinkubacki** [Sylius/Sylius#4217]
Is Sylius still support createNew() methods? I had no errors with Sylius 0.16 dev, after update to 0.16 I'm not able to create new product.

For example creating new products should work using product repository:
    $repository = $this->getContainer()->get('sylius.repository.product');
    $product = $repository->createNew();

Currently i have an error "Undefined method 'createNew'. The method name must start with either findBy or findOneBy!" when im trying to createNew any product or taxon.

Should it work or methods was changed and no longer supported?

**Comment by pjedrzejewski** [comment]
Sorry, UPGRADE is missing this super important note - You should now use ``sylius.factory.product->createNew()``. It also handles the master variant for you, so no need to bother with that. I will leave this open so that we add it to UPGRADE file later. Thanks for opening the issue!

**Comment by TheMadeleine** [comment]
Are we still planning to cover this issue  in the UPGRADE file? @pjedrzejewski
